import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Welcome.module.css'
import logo1 from '../assets/metapay-logo.svg'
import logo from '../assets/Logo.svg'

const Home: NextPage = () => {
  return (
    <div className="">
       <Head>
        <title>MetaPay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.svg" />
      </Head>

      <div className={styles.page}>

      <div className={styles.container}>
        <div className={styles.left}>
          <div className={styles.logo}>
            <Image src={logo1} alt="metapay logo" />
          </div>
            <h1 className={styles.subTitle}>MetaPay is replacing GoFundMe...</h1>
        </div>

          <div className={styles.right}>
            <h1 className={styles.welcome_description}>Your decentrialized home for help</h1>  
           <Link href="/">
            <button className={styles.button}>Start a MetaPay</button>
          </Link>
        </div>
      </div>
         </div>
         
      </div>
  )
}

export default Home
