import { useState, useEffect } from 'react'
import type { NextPage } from 'next'
// import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Welcome.module.css'
import logo1 from '../assets/metapay-logo.svg';
import Modal from '../components/WelcomeModal'

const Home: NextPage = () => {

      const [showModal, setShowModal] = useState(false);
    
      const openModal = () => {
        setShowModal(prev => !prev)
      }

  return (
    <div className="">
       <Head>
        <title>MetaPay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <div className={styles.page}>

      <div className={styles.container}>
        <div className={styles.left}>
          <div className={styles.logo}>
            <Image src={logo1} alt="metapay logo" />
          </div>
            <h1 className={styles.subTitle}>MetaPay it to Me...</h1>
        </div>

          <div className={styles.right}>
            <h1 className={styles.welcome_description}>Your decentrialized home for help</h1>  
        
            <button 
            className={styles.button} 
            onClick={openModal}
            >
              Start a MetaPay
            </button>
        </div>
              {/* ======== Modal is showing here ======== */}
             {/* @dev - I pass a props here and can be pass to the WelcomeModal.tsx */}
            <Modal showModal={showModal} setShowModal={setShowModal} />
      </div>
         </div>
         
      </div>
  )
}

export default Home
